src/app.py
from flask import Flask
from flask import render_template
import sys; sys.path.insert(0, ".")
from src.common.database import Database

app = Flask(__name__)
app.config.from_object('config')
app.secret_key = "gran2016"

@app.before_first_request
def init_db():
    Database.initialize()

@app.route('/')
def home():
    return render_template("home.jinja2")

from src.models.users.views import user_blueprint
from src.models.stores.views import store_blueprint
from src.models.alert.views import alert_blueprint

app.register_blueprint(user_blueprint, url_prefix="/users")
app.register_blueprint(store_blueprint, url_prefix="/stores")
app.register_blueprint(alert_blueprint, url_prefix="/alerts")

if __name__ == "__main__":
	app.run(host="0.0.0.0", debug=True)

src/models/alert/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask import session

from src.models.alert.alert import Alert
from src.models.items.item import Item
import src.models.users.decorators as user_decorators

alert_blueprint = Blueprint('alerts',__name__)

@alert_blueprint.route('/')
def index():
    return "This is the alerts index"

@alert_blueprint.route('/new', methods=['GET','POST'])
@user_decorators.requires_login
def create_alert():
    if request.method == 'POST':
        name = request.form['name']
        url = request.form['url']
        price_limit = float(request.form['price_limit'])
        #create item
        item = Item(name, url)
        item.save_to_mongo()

        alert = Alert(session['email'], price_limit, item._id)
        alert.load_item_price()

    return render_template('alerts/new_alert.jinja2')

@alert_blueprint.route('/edit/<string:alert_id>', methods=['GET','POST'])
@user_decorators.requires_login
def edit_alert(alert_id):
    if request.method == 'POST':
        pass
    return render_template('alerts/edit_alert.jinja2', alert= Alert.find_by_id(alert_id))


@alert_blueprint.route('/deactivate/<string:alert_id>')
@user_decorators.requires_login
def deactivate_alert(alert_id):
    Alert.find_by_id(alert_id).deactivate()
    return redirect(url_for('users.user_alerts'))

@alert_blueprint.route('/delete/<string:alert_id>')
@user_decorators.requires_login
def delete_alert(alert_id):
    Alert.find_by_id(alert_id).delete()
    return redirect(url_for('users.user_alerts'))

@alert_blueprint.route('/activate/<string:alert_id>')
@user_decorators.requires_login
def activate_alert(alert_id):
    Alert.find_by_id(alert_id).activate()
    return redirect(url_for('users.user_alerts'))

@alert_blueprint.route('/<string:alert_id>')
@user_decorators.requires_login
def get_alert_page(alert_id):
    alert = Alert.find_by_id(alert_id)
    return render_template('alerts/alert.jinja2', alert=alert)

@alert_blueprint.route('/for_users/<string:user_id>')
def get_alerts_for_user(user_id):
    pass

@alert_blueprint.route('/check_price/<string:alert_id>')
def check_alert_price(alert_id):
    Alert.find_by_id(alert_id).load_item_price()
    return redirect(url_for('.get_alert_page', alert_id=alert_id))

src/models/items/views.py
from flask import Blueprint

item_blueprint = Blueprint('items',__name__)

@item_blueprint.route('/item/<string:name>')
def item_page():
    pass

src/models/stores/views.py
from flask import Blueprint, render_template, request, redirect, url_for
import json
import src.models.users.decorators as user_decorators

from src.models.stores.store import Store

store_blueprint = Blueprint('stores',__name__)



@store_blueprint.route('/')
def index():
    stores = Store.all()
    return render_template("stores/store_index.jinja2", stores= stores)

@store_blueprint.route('/store/<string:store_id>')
def stores_page(store_id):
    return render_template("stores/store.jinja2", store=Store.get_by_id(store_id))

@store_blueprint.route('/edit/<string:store_id>',methods=['GET','POST'])
@user_decorators.requires_admin_permissions
def edit_store(store_id):
    store = Store.get_by_id(store_id)
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])

        store.name = name
        store.url_prefix = url_prefix
        store.tag_name = tag_name
        store.query = query
        store.save_to_mongo()
        return render_template(url_for('.index'))
    return render_template('stores/edit_store.jinja2', store=store)

@store_blueprint.route('/delete/<string:store_id>',methods=['GET'])
@user_decorators.requires_admin_permissions
def delete_store(store_id):
    Store.get_by_id(store_id).delete()
    return redirect(url_for('.index '))


@store_blueprint.route('/new', methods=['GET','POST'])
def create_store():
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])

        Store(name, url_prefix, tag_name, query).save_to_mongo()
        return redirect(url_for('.index'))

    return render_template('stores/new_store.jinja2')

src/models/users/views.py
from  flask import Blueprint, request, session, url_for, render_template
from werkzeug.utils import redirect
from src.models.users.user import User
import src.models.users.errors as UserErrors
import src.models.users.decorators as user_decorators

user_blueprint = Blueprint('users',__name__)

@user_blueprint.route('/login', methods=['GET', 'POST'])
def login_user():
    if request.method=='POST':
        email=request.form['email']
        password=request.form['password']

        try:
            if User.is_login_valid(email, password):
                session['email'] = email
                return redirect(url_for(".user_alerts"))
        except UserErrors.UserError as e:
            return e.message


    return render_template("users/login.jinja2")


@user_blueprint.route('/register', methods=['GET','POST'])
def register_user():
    if request.method=='POST':
        email=request.form['email']
        password=request.form['password']

        try:
            if User.register_user(email, password):
                session['email'] = email
                return redirect(url_for(".user_alerts"))
        except UserErrors.UserError as e:
            return e.message


    return render_template("users/register.jinja2")

@user_blueprint.route('/alerts')
@user_decorators.requires_login
def user_alerts():
    user = User.find_by_email(session['email'])
    alerts = user.get_alerts()

    return render_template('users/alerts.jinja2', alerts=alerts, prueba="Se puede")

@user_blueprint.route('/logout')
def logout_user():
    session['email'] = None
    return redirect(url_for('home'))

@user_blueprint.route('/check_alerts/<string:user_id>')
def check_user_alerts(user_id):
    pass

src/templates/alerts/alert.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Alert <small>for '{{ alert.item.name }}'</small></h1>
    </div>
    <p>last price found <strong>{{ alert.last_checked.strftime('%d-%m-%Y at %H:%M') }}</strong></p>
    <div class="panel panel-default">
        <div class="panel-body">
            <a class="btn btn-default" href="{{ alert.item.url }}" role="button">Visit Site</a>
            <a class="btn btn-warning" href="{{ url_for('alerts.edit_alert', alert_id=alert._id) }}" role="button">Edit Alert</a>
            {% if alert.active %}
            <a class="btn btn-danger" href="{{ url_for('alerts.deactivate_alert', alert_id= alert._id) }}" role="button">Deactivate Alert</a>
            {% else %}
            <a class="btn btn-success" href="{{ url_for('alerts.activate_alert', alert_id= alert._id) }}" role="button">Activate Alert</a>
            <a class="btn btn-danger" href="{{ url_for('alerts.delete_alert', alert_id=alert._id) }}">Delete Alert</a>
            {% endif %}
            <a class="btn btn-warning" href="{{ url_for('alerts.check_alert_price', alert_id=alert._id) }}" role="button">Check Alert Price</a>
        </div>
    </div>
{% endblock %}

src/templates/alerts/edit_alert.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

src/templates/alerts/new_alert.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Create Alert </h1>
    </div>
    <div class="form-size">
        <form method="post">
            <div class="form-group">
                <label for="name">Alert/Item Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Name">
            </div>
            <div class="form-group">
                <label for="url">URL</label>
                <input type="text" class="form-control" id="url" name="url" placeholder="http://...">
            </div>
            <div class="form-group">
                <label for="price_limit">Alert limit</label>
                <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="45.0" aria-describedby="priceLimitBlock">
                <p id="priceLimitBlock" class="help-block">We'll send you an email</p>
            </div>
            <button type="submit" class="btn btn-default">Create</button>
        </form>
    </div>
{% endblock %}

src/templates/base.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pricing _Services</title>
    {% include 'html_dependencies.jinja2' %}
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Price</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{{ url_for('stores.index')}}">Stores</a></li>
        <li><a href="{{ url_for('alerts.index')}}">Alerts</a></li>
      </ul>
        {% if session['email'] %}
        <ul class="nav navbar-nav navbar-right">
        <li><a href="{{ url_for('users.user_alerts')}}"><span class="glyphicon glyphicon-alert"></span>&nbsp;Your Alerts</a></li>
        <li><a href="{{ url_for('users.logout_user')}}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;Log Out</a></li>
      </ul>
        {% else %}
        <ul class="nav navbar-nav navbar-right">
        <li><a href="{{ url_for('users.register_user')}}"><span class="glyphicon glyphicon-user"></span>&nbsp;Sign up</a></li>
        <li><a href="{{ url_for('users.login_user')}}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;Login</a></li>
      </ul>
        {% endif %}
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="content container">
    {% block content %}

    {% endblock %}
</div>

</body>
</html>

src/templates/home.jinja2
{% extends "base.jinja2" %}
{% block content %}
<div>
    <h1>Pricing Service</h1>
    <p>We scan online store websites to alert you</p>
    <p>Just sing up</p>
    <p><a class="btn btn-primary btn-lg" href="{{ url_for('users.register_user') }}" role="button">Sign Up</a></p>
</div>
{% endblock %}

src/templates/html_dependencies.jinja2
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" ></script>
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
<script src="{{ url_for('static', filename='js/sample.js') }}" ></script>

src/templates/stores/edit_store.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Edit Store</h1>
    </div>
    <div class="form-size">
        <form method="POST">
            <div class="form-group">
                <label for="name">Store Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Store Name" value="{{ store.name }}">
            </div>
            <div class="form-group">
                <label for="url_prefix">Url</label>
                <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="Store URL" value="{{ store.url_prefix }}">
            </div>
            <div class="form-group">
                <label for="tag_name">Tag Name</label>
                <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="Tag Name" value="{{ store.tag_name }}">
            </div>
             <div class="form-group">
                <label for="query">Query</label>
                <input type="text" class="form-control" id="query" name="query" placeholder="Tag Name" value="{{ store.query | tojson }}">
            </div>
            <button type="submit" class="btn btn-default"><Update>Update</Update></button>
        </form>
    </div>
{% endblock %}

src/templates/stores/new_store.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Create Store</h1>
    </div>
    <div class="form-size">
        <form method="POST">
            <div class="form-group">
                <label for="name">Store Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Store Name">
            </div>
            <div class="form-group">
                <label for="url_prefix">Url</label>
                <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="Store URL">
            </div>
            <div class="form-group">
                <label for="tag_name">Tag Name</label>
                <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="Tag Name" value="spam">
            </div>
             <div class="form-group">
                <label for="query">Query</label>
                <input type="text" class="form-control" id="query" name="query" placeholder="Tag Name" value="spam">
            </div>
            <button type="submit" class="btn btn-default">Create</button>
        </form>
    </div>
{% endblock %}

src/templates/stores/store.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Store <small>{{ store.name }}</small></h1>
    </div>
    <p>
        ALL URL'S IN THIS STORE
    </p>
    <div class="panel panel-default"></div>
    <div class="panel-body">
        <a class="btn btn-warning" href="{{ url_for('stores.edit_store', store_id=store._id) }}" role="button">Edit Store</a>
        <a class="btn btn-danger" href="{{ url_for('stores.delete_store', store_id=store._id) }}" role="button">Delete Store</a>
    </div>
{% endblock %}

src/templates/stores/store_index.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Stores<small>list of supported stores</small></h1>
    </div>

    <div class="list-group">
    {% for store in stores %}
            <a href="{{ url_for('stores.stores_page', store_id=store._id) }}" class="list-group-item">
            <h4 class="list-group-item-title">{{ store.name }}</h4>
            <p class="list-group-item-text">{{ store.url_prefix }}</p>
            </a>
    {% endfor %}
    </div>
{% if session['email'] in config.ADMINS %}
    <a class="btn btn-success" href="{{ url_for('stores.create_store') }}">
        <span class="glyphicon glyphicon-plus"></span> Create new
    </a>
{% endif %}
{% endblock %}

src/templates/users/alerts.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Alerts</h1>
    </div>
    {% for alert in alerts  %}
    <div class="list-group">
        <a href="{{ url_for('alerts.get_alert_page', alert_id=alert._id) }}" class="list-group-item {{ 'list-group-item-warning' if not alert.active else '' }}">
            <h4 class="list-group-item-heading">Alert for {{ alert.item.name }}</h4>
            <p class="list-group-item-text">Last price found {{ alert.item.price }}<br/>
            Last checked on {{ alert.last_checked.strftime("%d-%m-%Y at %H:%M") }}
            </p>
        </a>
    </div>
    {% endfor %}
    <a class="btn btn-success" href="{{ url_for('alerts.create_alert') }}">Create Alert</a>
{% endblock %}

src/templates/users/login.jinja2
 {% extends "base.jinja2" %}
{% block content %}
 <div>
  <form class="form-size" method="post" action="{{ url_for('users.login_user') }}">
         <div class="form-group">
            <label for="email">Email address</label>
             <input type="email" class="form-control" id="email" name="email" placeholder="Email">
         </div>
         <div class="form-group">
            <label for="password">Password</label>
             <input type="password" class="form-control" id="password" name="password" placeholder="Password">
         </div>
         <button type="submit" class="btn btn-default">Log in</button>
     </form>
      </div>
{% endblock%}

src/templates/users/register.jinja2
{% extends "base.jinja2" %}
{% block content %}
 <div>
     <form class="form-size" method="post" action="{{ url_for('users.register_user') }}">
         <div class="form-group">
            <label for="email">Email address</label>
             <input type="email" class="form-control" id="email" name="email" placeholder="Email">
         </div>
         <div class="form-group">
            <label for="password">Password</label>
             <input type="password" class="form-control" id="password" name="password" placeholder="Password">
         </div>
         <button type="submit" class="btn btn-default">Sign Up</button>
     </form>
 </div>
{% endblock%}